services:
  - type: web
    name: django-backend
    runtime: python
    buildCommand: |
      pip install -r requirements.txt && \
      python manage.py collectstatic --noinput
    startCommand: |
      echo "Running database migrations..." && \
      python manage.py migrate --noinput && \
      echo "Creating superuser if not exists..." && \
      python manage.py create_initial_superuser || echo "Superuser creation failed or not needed" && \
      echo "Starting gunicorn..." && \
      gunicorn config.wsgi:application
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.11.9
